In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('tmdb_5000_movies.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
budget                  4803 non-null int64
genres                  4803 non-null object
homepage                1712 non-null object
id                      4803 non-null int64
keywords                4803 non-null object
original_language       4803 non-null object
original_title          4803 non-null object
overview                4800 non-null object
popularity              4803 non-null float64
production_companies    4803 non-null object
production_countries    4803 non-null object
release_date            4802 non-null object
revenue                 4803 non-null int64
runtime                 4801 non-null float64
spoken_languages        4803 non-null object
status                  4803 non-null object
tagline                 3959 non-null object
title                   4803 non-null object
vote_average            4803 non-null float64
vote_count              4803 non-null int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.5+ KB

In [4]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [5]:
df2=df.dropna()
df2

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004
11,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.mgm.com/view/movie/234/Quantum-of-S...,10764,"[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",en,Quantum of Solace,Quantum of Solace continues the adventures of ...,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2008-10-30,586090727,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965
12,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,58,"[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",en,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,145.847379,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""JM"", ""name"": ""Jamaica""}, {""is...",2006-06-20,1065659812,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246
13,255000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://disney.go.com/the-lone-ranger/,57201,"[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-07-03,89289910,149.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never Take Off the Mask,The Lone Ranger,5.9,2311
14,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.manofsteel.com/,49521,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Man of Steel,A young boy learns that he has extraordinary p...,99.398009,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2013-06-12,662845518,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You will believe that a man can fly.,Man of Steel,6.5,6359
16,220000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://marvel.com/avengers_movie/,24428,"[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",en,The Avengers,When an unexpected enemy emerges and threatens...,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-04-25,1519557910,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Some assembly required.,The Avengers,7.4,11776
17,380000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://disney.go.com/pirates/index-on-stranger...,1865,"[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,135.413856,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-05-14,1045713802,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948
18,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://www.sonypictures.com/movies/meninblack3/,41154,"[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",en,Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,"[{""name"": ""Amblin Entertainment"", ""id"": 56}, {...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-23,624026776,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They are back... in time.,Men in Black 3,6.2,4160
19,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.thehobbit.com/,122917,"[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",en,The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...,120.965743,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2014-12-10,956019788,144.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760
20,215000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.theamazingspiderman.com,1930,"[{""id"": 1872, ""name"": ""loss of father""}, {""id""...",en,The Amazing Spider-Man,Peter Parker is an outcast high schooler aband...,89.866276,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-06-27,752215857,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The untold story begins.,The Amazing Spider-Man,6.5,6586
21,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.robinhoodthemovie.com/,20662,"[{""id"": 4147, ""name"": ""robin hood""}, {""id"": 43...",en,Robin Hood,When soldier Robin happens upon the dying Robe...,37.668301,"[{""name"": ""Imagine Entertainment"", ""id"": 23}, ...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2010-05-12,310669540,140.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"Rise and rise again, until lambs become lions.",Robin Hood,6.2,1398
22,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.thehobbit.com/,57158,"[{""id"": 603, ""name"": ""elves""}, {""id"": 604, ""na...",en,The Hobbit: The Desolation of Smaug,"The Dwarves, Bilbo and Gandalf have successful...",94.370564,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2013-12-11,958400000,161.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Beyond darkness... beyond desolation... lies t...,The Hobbit: The Desolation of Smaug,7.6,4524
23,180000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.goldencompassmovie.com/index_german...,2268,"[{""id"": 392, ""name"": ""england""}, {""id"": 1461, ...",en,The Golden Compass,"After overhearing a shocking secret, precociou...",42.990906,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2007-12-04,372234864,113.0,"[{""iso_639_1"": ""is"", ""name"": ""\u00cdslenska""},...",Released,There are worlds beyond our own - the compass ...,The Golden Compass,5.8,1303
25,200000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://www.titanicmovie.com,597,"[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",en,Titanic,"84 years later, a 101-year-old woman named Ros...",100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1997-11-18,1845034188,194.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Nothing on Earth could come between them.,Titanic,7.5,7562
26,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://marvel.com/captainamericapremiere,271110,"[{""id"": 393, ""name"": ""civil war""}, {""id"": 6091...",en,Captain America: Civil War,"Following the events of Age of Ultron, the col...",198.372395,"[{""name"": ""Studio Babelsberg"", ""id"": 264}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-04-27,1153304495,147.0,"[{""iso_639_1"": ""ro"", ""name"": ""Rom\u00e2n\u0103...",Released,Divided We Fall,Captain America: Civil War,7.1,7241
28,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-06-09,1513528810,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The park is open.,Jurassic World,6.5,8662
29,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.skyfall-movie.com,37724,"[{""id"": 470, ""name"": ""spy""}, {""id"": 4289, ""nam...",en,Skyfall,When Bond's latest assignment goes gravely wro...,93.004993,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2012-10-25,1108561013,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Think on your sins.,Skyfall,6.9,7604
30,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spider-man2/,558,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 2,Peter Parker is going through a major identity...,35.149586,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-06-25,783766341,127.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,There's a hero in all of us.,Spider-Man 2,6.7,4321
31,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/ironman3,68721,"[{""id"": 949, ""name"": ""terrorist""}, {""id"": 5597...",en,Iron Man 3,When Tony Stark's world is torn apart by a for...,77.682080,"[{""name"": ""Marvel Studios"", ""id"": 420}]","[{""iso_3166_1"": ""CN"", ""name"": ""China""}, {""iso_...",2013-04-18,1215439994,130.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Unleash the power behind the armor.,Iron Man 3,6.8,8806
32,200000000,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 14, ""...",http://disney.go.com/wonderland/,12155,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,Alice in Wonderland,"Alice, an unpretentious and individual 19-year...",78.530105,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-03-03,1025491110,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You're invited to a very important date.,Alice in Wonderland,6.4,4645
35,150000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.transformersmovie.com/,8373,"[{""id"": 1160, ""name"": ""egypt""}, {""id"": 1670, ""...",en,Transformers: Revenge of the Fallen,Sam Witwicky leaves the Autobots behind for a ...,21.939663,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-06-19,836297228,150.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Revenge is coming.,Transformers: Revenge of the Fallen,6.0,3138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4655,250000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10751, ""n...",http://www.thechristmasbunny.com/,77934,[],en,The Christmas Bunny,The Christmas Bunny tells the story of a lonel...,0.065103,"[{""name"": ""Honey Creek Pictures"", ""id"": 8077}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-28,0,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Everybody needs some bunny to love.,The Christmas Bunny,5.7,7
4664,230000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name...",http://www.bronsonthemovie.com,18533,"[{""id"": 378, ""name"": ""prison""}, {""id"": 1533, ""...",en,Bronson,A young man who was sentenced to 7 years in pr...,18.450613,"[{""name"": ""EM Media"", ""id"": 1917}, {""name"": ""A...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",2008-10-09,2260712,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Man. The Myth. The Celebrity.,Bronson,6.9,733
4666,225000,"[{""id"": 10769, ""name"": ""Foreign""}, {""id"": 99, ...",http://detroitfirefilm.org/,139948,"[{""id"": 933, ""name"": ""michigan""}, {""id"": 6711,...",en,Burn,"A character-driven, action-packed documentary ...",0.126676,"[{""name"": ""Apostle Productions"", ""id"": 23648}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-11-01,111300,86.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,One Year on the Front Lines of the Battle to S...,Burn,6.9,6
4675,200000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.thegracecardmovie.com/,54897,"[{""id"": 2783, ""name"": ""family's daily life""}, ...",en,The Grace Card,Everything can change in an instant ... and ta...,0.616283,"[{""name"": ""GraceWorks Pictures"", ""id"": 33632}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-02-25,2295733,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never Underestimate The Power Of Grace ...,The Grace Card,6.5,10
4687,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.gooddickthefilm.com/,14758,"[{""id"": 738, ""name"": ""sexuality""}, {""id"": 1253...",en,Good Dick,"A fidgety, wisecracking video store clerk deve...",1.948435,"[{""name"": ""Good Dick"", ""id"": 3015}, {""name"": ""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2008-10-03,0,86.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A hard man... is good to find.,Good Dick,6.1,34
4688,0,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://manfromearth.com/,13363,"[{""id"": 490, ""name"": ""philosophy""}, {""id"": 132...",en,The Man from Earth,An impromptu goodbye party for Professor John ...,31.339015,"[{""name"": ""Falling Sky Entertainment"", ""id"": 2...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-06-10,0,87.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,From one of the acclaimed writers of Star Trek...,The Man from Earth,7.7,687
4695,180000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",http://www.miramax.com/movie/children-of-heaven/,21334,"[{""id"": 1155, ""name"": ""brother sister relation...",fa,Ø¨Ú†Ù‡â€ŒÙ‡Ø§ÛŒ Ø¢Ø³Ù…Ø§Ù†,Zohre's shoes are gone; her older brother Ali ...,7.072118,"[{""name"": ""The Institute for the Intellectual ...","[{""iso_3166_1"": ""IR"", ""name"": ""Iran""}]",1997-08-01,900000,89.0,"[{""iso_639_1"": ""fa"", ""name"": ""\u0641\u0627\u06...",Released,A Little Secret...Their Biggest Adventure!,Children of Heaven,7.8,112

In [6]:
df2.isnull().sum().sum()

0

In [7]:
df3 = df.dropna(how='all')
df3.shape

(4803, 20)

In [8]:
df.dropna(thresh=4000, axis=1, inplace=True)

In [9]:
df.isnull().sum().sum()

6

In [10]:
df.isnull().sum()

budget                  0
genres                  0
id                      0
keywords                0
original_language       0
original_title          0
overview                3
popularity              0
production_companies    0
production_countries    0
release_date            1
revenue                 0
runtime                 2
spoken_languages        0
status                  0
title                   0
vote_average            0
vote_count              0
dtype: int64

In [11]:
df['overview'].fillna(value='Overview not available', inplace=True)

In [12]:
df['overview'].isnull().sum()

0

In [13]:
df['release_date'][df['release_date'].isnull()]

4553    NaN
Name: release_date, dtype: object

In [14]:
df['release_date'][4552:4555]

4552    2012-03-28
4553           NaN
4554    2015-03-10
Name: release_date, dtype: object

In [17]:
df['release_date'].fillna(method='ffill', inplace=True)

In [18]:
df['runtime'].mean()

106.87585919600083

In [19]:
df['runtime'].fillna(value=df['runtime'].mean(), inplace=True)

In [20]:
df.isnull().sum().sum()

0

In [21]:
import pandas as pd
df =  pd.DataFrame({ 'color': ['blue','blue','red','red','blue'], 'value': [2,1,3,3,2]})

In [22]:
df

  color  value
0  blue      2
1  blue      1
2   red      3
3   red      3
4  blue      2

In [23]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [24]:
df.duplicated(keep='last')

0     True
1    False
2     True
3    False
4    False
dtype: bool

In [25]:
df.duplicated(keep=False)

0     True
1    False
2     True
3     True
4     True
dtype: bool

In [26]:
df.loc[df.duplicated(),:]

  color  value
3   red      3
4  blue      2

In [27]:
df.drop_duplicates()

  color  value
0  blue      2
1  blue      1
2   red      3

In [28]:
df.drop_duplicates(['value'])

  color  value
0  blue      2
1  blue      1
2   red      3

In [29]:
df.drop_duplicates(['color'])

  color  value
0  blue      2
2   red      3

In [30]:
import pandas as pd
df = pd.read_table('http://bit.ly/chiporders')

In [32]:
df.duplicated().sum()

59

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

In [35]:
df.duplicated("order_id").sum()

2788

In [36]:
df.duplicated("quantity").sum()

4613

In [37]:
df.duplicated("item_name").sum()

4572

In [38]:
df.duplicated("choice_description").sum()

3578

In [39]:
df.duplicated("item_price").sum()

4544

In [40]:
dups = []
for col in df.columns:
    x = df.duplicated([col]).sum()
    dups.append(x)

In [41]:
dups

[2788, 4613, 4572, 3578, 4544]

In [43]:
df.duplicated(['order_id', 'item_name', 'item_price']).sum()

249

In [44]:
df.drop_duplicates(['order_id', 'item_name', 'item_price'])

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
20,10,1,Chips and Guacamole,NaN,$4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
24,12,1,Izze,[Grapefruit],$3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
28,14,1,Canned Soda,[Dr. Pepper],$1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
...,...,...,...,...,...
4588,1824,1,Chips and Guacamole,NaN,$4.45
4589,1825,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$11.75
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",$11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",$11.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
4596,1826,1,Chips and Guacamole,NaN,$4.45
4597,1826,1,Canned Soft Drink,[Nestea],$1.25
4598,1826,1,Bottled Water,NaN,$1.50
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
4600,1827,1,Chips and Guacamole,NaN,$4.45
4601,1827,1,Canned Soft Drink,[Diet Coke],$1.25
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4605,1828,1,Chips and Guacamole,NaN,$4.45
4606,1828,1,Canned Soft Drink,[Coke],$1.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",$11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4609,1829,1,Canned Soft Drink,[Sprite],$1.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75